name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: 'pip' # Enable caching for pip installs based on requirements file
        cache-dependency-path: src/app/dev-requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/app/dev-requirements.txt

    - name: Lint with flake8
      run: |
        # Check for critical errors (Syntax, Undefined Names - excluding F824)
        python -m flake8 src/app --count --select=E9,F63,F7 --show-source --statistics
        # Check for other style issues (ignore F824 again)
        python -m flake8 src/app --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics --extend-ignore=F824

    - name: Test with pytest and Generate Coverage Report
      run: |
        python -m pytest \
          --cov=src/app \
          --cov-report=xml \
          --cov-report=term-missing \
          --cov-fail-under=70 \
          tests

    # Optional: Upload coverage reports to Codecov
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v4.0.1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }} # Create this secret in GitHub settings
    #     # Optional: specify coverage file if not coverage.xml
    #     # files: ./coverage.xml
    #     # Optional: flags for categorizing coverage
    #     # flags: unittests
    #     # Optional: name for the commit
    #     # name: codecov-umbrella
    #     # Optional: fail if upload fails
    #     # fail_ci_if_error: true 